/**
 * Cross-language state.json round-trip — PLAN.md cutover criterion #2 (TS half).
 *
 * agents/{adw_id}/state.json is the sole cross-language contract between the
 * Python adw/ pipeline and this TypeScript engine (PLAN.md D4). With no shared
 * code across the boundary, the only thing that keeps two reimplementations
 * from drifting is a contract tested from BOTH sides. This is the TS half;
 * adw/test_cross_language_state.py is the twin. Together they prove the three
 * sub-criteria of cutover criterion #2:
 *
 *   (i)   both engines' state.json validate against adw/state.schema.json;
 *   (ii)  a Python-engine-produced state.json is loadable+resumable by the TS
 *         AdwState.load() (the "and vice-versa" half of criterion #2(ii));
 *   (iii) the two engines' documents agree on every v1 field, differing only by
 *         the TS-additive keys (engine/runner/total_cost_usd).
 *
 * The committed fixtures live in adw/fixtures/cross_language/ — the shared
 * contract directory, next to state.schema.json (read here exactly as the
 * engine-parity suite already reads the schema). A drift guard regenerates the
 * ts-produced fixture from the real writer so it can never silently rot; the
 * py-produced fixture is regenerated by the Python suite's twin drift guard.
 * Both fixtures encode the same logical run (same adw_id, same v1 values).
 */

import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { REPO_ROOT } from '../src/common.js';
import { AdwState, setAgentsDir, STATE_FILENAME } from '../src/state.js';
import { validate, type Schema } from './helpers/state-schema.js';

const FIXTURE_DIR = join(REPO_ROOT, 'adw', 'fixtures', 'cross_language');
const PY_FIXTURE = join(FIXTURE_DIR, 'py-produced-state.json');
const TS_FIXTURE = join(FIXTURE_DIR, 'ts-produced-state.json');
const SCHEMA = JSON.parse(readFileSync(join(REPO_ROOT, 'adw', 'state.schema.json'), 'utf8')) as Schema;

/** The canonical run id both fixtures share (a valid 8-char hex id). */
const ADW_ID = '00000000';

/**
 * The full ordered phase-completion list of a finished run: setup (control) +
 * the nine agent phases in AGENT_PHASES order + merge (control). Both engines
 * record the same phase names (templates and phase order are shared verbatim).
 */
const COMPLETED_PHASES = [
  'setup',
  'classify',
  'plan',
  'implement',
  'tests',
  'resolve',
  'e2e',
  'review',
  'patch',
  'document',
  'merge',
];

/** The canonical v1 fields (the cross-language equivalence projection). */
const V1_KEYS = [
  'adw_id',
  'schema_version',
  'issue_number',
  'issue_class',
  'branch_name',
  'base',
  'plan_file',
  'pr_number',
  'pr_url',
  'commit_message',
  'pr_body',
  'review_findings',
  'completed_phases',
] as const;

/** Keys the TS engine adds additively (PLAN.md D4); the Python reader drops them. */
const TS_ADDITIVE_KEYS = ['engine', 'runner', 'work_item', 'change_request', 'total_cost_usd'] as const;

/**
 * Rebuild the exact state the committed ts-produced fixture was made from. Kept
 * in lockstep with the generator so the drift guard is meaningful: if the
 * writer or these values change without regenerating, the byte-compare fails.
 */
function canonicalTsState(): AdwState {
  const state = new AdwState({
    adwId: ADW_ID,
    issueNumber: '5',
    issueClass: 'feat',
    branchName: 'feat/5-00000000-cross-language-contract',
    base: 'main',
    planFile: 'specs/5-cross-language-contract.md',
    prNumber: 42,
    prUrl: 'https://github.com/kortiene/mx-agent/pull/42',
    commitMessage: 'feat: cross-language state contract\n\ncloses #5',
    prBody: 'Closes #5\n\nProves agents/{adw_id}/state.json round-trips across the py and ts engines.',
    reviewFindings: [
      { severity: 'blocker', description: 'example blocker the patch gate must fix', location: 'adw/_state.py:120' },
    ],
    engine: 'ts',
    runner: 'claude',
    workItem: { provider: 'github', type: 'issue', id: '5', number: 5, title: 'Cross-language contract' },
    changeRequest: {
      provider: 'github',
      type: 'pull_request',
      id: '42',
      number: 42,
      url: 'https://github.com/kortiene/mx-agent/pull/42',
    },
    totalCostUsd: 0.4242,
  });
  for (const phase of COMPLETED_PHASES) {
    state.markDone(phase);
  }
  return state;
}

function v1Projection(doc: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of V1_KEYS) {
    if (key in doc) {
      out[key] = doc[key];
    }
  }
  return out;
}

function readFixtureDoc(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
}

describe('cross-language state.json contract (TS half)', () => {
  let tmp: string;

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), 'adw-xlang-'));
    setAgentsDir(tmp);
  });

  afterEach(() => {
    setAgentsDir(null);
    rmSync(tmp, { recursive: true, force: true });
  });

  describe('drift guard', () => {
    // Regenerate after an intentional change by re-running the generator
    // documented in the PR (the real writer with canonicalTsState()'s values).
    it('the TS writer output byte-matches the committed ts-produced fixture', () => {
      const state = canonicalTsState();
      state.save();
      const produced = readFileSync(state.statePath(), 'utf8');
      const committed = readFileSync(TS_FIXTURE, 'utf8');
      expect(produced, 'ts-produced fixture is stale; regenerate it').toBe(committed);
    });
  });

  describe('criterion #2(ii): a Python state.json loads+resumes under the TS reader', () => {
    beforeEach(() => {
      // Stage the Python-produced fixture where AdwState.load() will find it.
      const workspace = join(tmp, ADW_ID);
      mkdirSync(workspace, { recursive: true });
      writeFileSync(join(workspace, STATE_FILENAME), readFileSync(PY_FIXTURE, 'utf8'), 'utf8');
    });

    it('preserves every v1 field', () => {
      const loaded = AdwState.load(ADW_ID);
      expect(loaded).not.toBeNull();
      expect(loaded!.adwId).toBe(ADW_ID);
      expect(loaded!.schemaVersion).toBe(1);
      expect(loaded!.issueNumber).toBe('5');
      expect(loaded!.issueClass).toBe('feat');
      expect(loaded!.branchName).toBe('feat/5-00000000-cross-language-contract');
      expect(loaded!.base).toBe('main');
      expect(loaded!.planFile).toBe('specs/5-cross-language-contract.md');
      expect(loaded!.prNumber).toBe(42);
      expect(loaded!.prUrl).toBe('https://github.com/kortiene/mx-agent/pull/42');
      expect(loaded!.commitMessage).toBe('feat: cross-language state contract\n\ncloses #5');
      expect(loaded!.prBody).toBe(
        'Closes #5\n\nProves agents/{adw_id}/state.json round-trips across the py and ts engines.',
      );
    });

    it('keeps the resume contract intact (every phase done, short-circuits)', () => {
      const loaded = AdwState.load(ADW_ID);
      expect(loaded!.completedPhases).toEqual(COMPLETED_PHASES);
      for (const phase of COMPLETED_PHASES) {
        expect(loaded!.isDone(phase), `resume would re-run ${phase}`).toBe(true);
      }
    });

    it('round-trips the blocker finding the patch gate depends on', () => {
      const loaded = AdwState.load(ADW_ID);
      expect(loaded!.reviewFindings).toHaveLength(1);
      expect(loaded!.reviewFindings[0]!['severity']).toBe('blocker');
    });

    it('leaves the TS-additive fields unset (Python never wrote them)', () => {
      const loaded = AdwState.load(ADW_ID);
      expect(loaded!.engine).toBeUndefined();
      expect(loaded!.runner).toBeUndefined();
      expect(loaded!.totalCostUsd).toBeUndefined();
    });
  });

  describe('criterion #2(iii): the two engines agree on every v1 field', () => {
    it('v1 projections are identical', () => {
      expect(v1Projection(readFixtureDoc(TS_FIXTURE))).toEqual(v1Projection(readFixtureDoc(PY_FIXTURE)));
    });

    it('only the ts fixture carries the additive keys', () => {
      const tsDoc = readFixtureDoc(TS_FIXTURE);
      const pyDoc = readFixtureDoc(PY_FIXTURE);
      for (const key of TS_ADDITIVE_KEYS) {
        expect(tsDoc, `ts fixture should carry ${key}`).toHaveProperty(key);
        expect(pyDoc, `py fixture must not carry ${key}`).not.toHaveProperty(key);
      }
    });

    it('the py fixture has exactly the v1 keys', () => {
      expect(Object.keys(readFixtureDoc(PY_FIXTURE)).sort()).toEqual([...V1_KEYS].sort());
    });

    it('the ts fixture has exactly the v1 keys plus the additive keys (no other leakage)', () => {
      // Symmetric with the py-fixture guard above: pins the TS document's full
      // key set so a future TS-writer field that is not declared in
      // TS_ADDITIVE_KEYS fails loudly here (and forces a conscious contract
      // update), independent of the drift guard.
      expect(Object.keys(readFixtureDoc(TS_FIXTURE)).sort()).toEqual([...V1_KEYS, ...TS_ADDITIVE_KEYS].sort());
    });
  });

  describe('criterion #2(i): both engines validate against state.schema.json', () => {
    it('the py-produced fixture validates', () => {
      expect(validate(readFixtureDoc(PY_FIXTURE), SCHEMA)).toEqual([]);
    });

    it('the ts-produced fixture validates', () => {
      expect(validate(readFixtureDoc(TS_FIXTURE), SCHEMA)).toEqual([]);
    });
  });
});
